base: 'https://jseiler.ddev.site/'
rootPageId: 1
websiteTitle: 'Jens der Denker'

dependencies:
  - jensseiler/jssitepackage

languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_DE.UTF-8
    flag: de