base: 'https://jseiler.ddev.site/'
dependencies:
  - jensseiler/jssitepackage
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_DE.UTF-8
    navigationTitle: English
    flag: de
rootPageId: 1
websiteTitle: ''