base: 'https://jseiler.ddev.site/'
dependencies:
  - jensseiler/jssitepackage
  - typo3/fluid-styled-content-css
  - typo3/fluid-styled-content
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_DE.UTF-8
    navigationTitle: Deutsch
    flag: de
rootPageId: 1
websiteTitle: 'JS Sitepackage'
sets:
  typo3/fluid-styled-content-css:
    setup: true
  jensseiler/jssitepackage:
    setup: true